runtime: python311
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  # REPLACE WITH YOUR ACTUAL API KEY BEFORE DEPLOYING
  GEMINI_API_KEY: 'INSERT_YOUR_API_KEY_HERE'

handlers:
# Handle API requests via Flask
- url: /api/.*
  script: auto

# Serve the main HTML file
- url: /
  static_files: index.html
  upload: index.html
  secure: always

# Serve index.html for root requests
- url: /index.html
  static_files: index.html
  upload: index.html
  secure: always

# Serve images
- url: /(.*\.(png|jpg|jpeg|gif|svg|webp|ico))
  static_files: \1
  upload: .*\.(png|jpg|jpeg|gif|svg|webp|ico)
  secure: always
  http_headers:
    Cache-Control: "public, max-age=86400"

# Serve any other static files
- url: /(.*)
  static_files: \1
  upload: .*
  secure: always
